package de.adito.aditoweb.nbm.brackets.listener;

import org.jetbrains.annotations.NotNull;

import javax.swing.text.JTextComponent;

/**
 * If a opening tag was deleted by backspace,
 * the autogenerated closing tag should be deleted too
 *
 * @author w.glanzer, 17.11.2022
 */
class DeleteClosingTagListener extends AbstractTagListener
{

  @Override
  protected boolean handleCharDeleted0(@NotNull JTextComponent pTextComponent, char pChar) throws Exception
  {
    // check, if nothing is selected
    if (pTextComponent.getSelectionEnd() - pTextComponent.getSelectionStart() <= 0)
    {
      int caretPosition = pTextComponent.getCaretPosition();
      if (caretPosition < pTextComponent.getText().length())
      {
        char nextChar = pTextComponent.getText(caretPosition, 1).toCharArray()[0];
        if (nextChar == TAG_MAPPING.get(pChar))
        {
          pTextComponent.getDocument().remove(caretPosition, 1);
          return true;
        }
      }
    }

    return false;
  }

}
